---
- hosts: wordpress
  become: true
  pre_tasks:
      - name: Update the system
        tags: update
        ansible.builtin.apt:
          update_cache: yes
          upgrade: dist


  hosts: wordpress
  roles:
    - wordpress
